### ISSUE TITLE
Please add a license file and a screenshot

### ISSUE THREAD

**Issue by unixorn** [nylo-andry/zsh-themes#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

**Comment by fvnilo** [comment]
Thank you for your interest. I added a license file and a screenshot like you recommended. Have a nice day.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/750, thanks!
